### ISSUE TITLE
关于PluginFilter

### ISSUE THREAD

**Issue by ooocici** [2YSP/ship-gate#2]
```java
@Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
        String appName = parseAppName(exchange);
        if (CollectionUtils.isEmpty(ServiceCache.getAllInstances(appName))) {
            throw new ShipException(ShipExceptionEnum.SERVICE_NOT_FIND);
        }
        PluginChain pluginChain = new PluginChain(properties, appName);
        pluginChain.addPlugin(new DynamicRoutePlugin(properties));
        pluginChain.addPlugin(new AuthPlugin(properties));
        return pluginChain.execute(exchange, pluginChain);
    }
```
网关每次执行都需要创建pluginChain对象，为什么不将该对象设置为常亮使用呢？

**Comment by 2YSP** [comment]
PluginChain的addPlugin方法会根据当前应用开启了那些插件来动态设置的，所以对不同的appName而言PluginChain是不同的。
`  public void addPlugin(ShipPlugin shipPlugin) {
        if (plugins == null) {
            plugins = new ArrayList<>();
        }
        if (!PluginCache.isEnabled(appName, shipPlugin.name())) {
            return;
        }
        plugins.add(shipPlugin);
        // order by the plugin's order
        plugins.sort(Comparator.comparing(ShipPlugin::order));
    }`
对应的场景就是订单服务需要插件A,B,C，但是用户服务只需要插件A,所以组成的链是不一样的。

**Comment by 2YSP** [comment]
PluginChain的addPlugin方法会根据当前应用开启了那些插件来动态设置的，所以对不同的appName而言PluginChain是不同的。
```java
public void addPlugin(ShipPlugin shipPlugin) {
        if (plugins == null) {
            plugins = new ArrayList<>();
        }
        if (!PluginCache.isEnabled(appName, shipPlugin.name())) {
            return;
        }
        plugins.add(shipPlugin);
        // order by the plugin's order
        plugins.sort(Comparator.comparing(ShipPlugin::order));
    }
```
对应的场景就是订单服务需要插件A,B,C，但是用户服务可能只需要插件A,所以组成的链是不一样的。

**Comment by ooocici** [comment]
忽略了这块逻辑，谢谢。
